apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: todo-app

spec:
  selector:
    app: django-label
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30009 
    #you can choose nodeport between 30000-32000
